[package]

name = "rustfft"
version = "6.4.1"
authors = ["Allen Welkie <allen.welkie at gmail>", "Elliott Mahler <join.together at gmail>"]
edition = "2021"
rust-version = "1.77"

description = "High-performance FFT library written in pure Rust."
documentation = "https://docs.rs/rustfft/"
repository = "https://github.com/ejmahler/RustFFT"
keywords = ["fft", "dft", "discrete", "fourier", "transform"]
categories = ["algorithms", "compression", "multimedia::encoding", "science"]
license = "MIT OR Apache-2.0"

[features]
default = ["avx", "sse", "neon"]

# On x86_64, the "avx" feature enables compilation of AVX-acclerated code. 
# Similarly, the "sse" feature enables compilation of SSE-accelerated code. 
# Enabling these improves performance if the client CPU supports AVX or SSE, while disabling them reduces compile time and binary size.
# If both are enabled, RustFFT will use AVX if the CPU supports it. If not, it will check for SSE4.1.
# If neither instruction set is available, it will fall back to the scalar code.  
#
# On AArch64, the "neon" feature enables compilation of Neon-accelerated code.
#
# On wasm32, the "wasm_simd" feature enables compilation of Wasm SIMD accelerated code.
#
# For all of the above features, on every platform other than the intended platform for the feature, these features do nothing, and RustFFT will behave like they are not set.
avx = []
sse = []
neon = []
wasm_simd = []


[dependencies]
num-complex = "0.4"
num-traits = "0.2"
num-integer = "^0.1.40"
strength_reduce = "0.2.4"
transpose = "0.2"
primal-check = "0.3.3"

[dev-dependencies]
criterion = { version = "0.5", default-features = false }

rand = "0.9"
getrandom = {version = "0.3", features = ["wasm_js"]}
wasm-bindgen-test = "^0.3.36"

# These are in the dependency tree of criterion. These need to be pinned for the MSRV tests
clap = { version = "=4.5.32", default-features = false, features = ["std"] }
half = { version = "=2.4.1", default-features = false }

[[bench]]
name = "bench_check_neon_2to1024"
harness = false

[[bench]]
name = "bench_check_scalar_2to1024"
harness = false

[[bench]]
name = "bench_check_sse_2to1024"
harness = false

[[bench]]
name = "bench_compare_scalar_neon"
harness = false

[[bench]]
name = "bench_compare_scalar_sse_avx"
harness = false

[[bench]]
name = "bench_compare_scalar_wasm_simd"
harness = false

[[bench]]
name = "bench_rustfft"
harness = false

[[bench]]
name = "bench_rustfft_neon"
harness = false

[[bench]]
name = "bench_rustfft_scalar"
harness = false

[[bench]]
name = "bench_rustfft_sse"
harness = false

[[bench]]
name = "bench_rustfft_wasm_simd"
harness = false

[[bench]]
name = "compare_3n2m_strategies"
harness = false
