import sys
from matplotlib import pyplot as plt
import numpy as np
from read_bench_series import read_benches

fnames = sys.argv[1:]
data = read_benches(fnames)

length = [2, 3, 4, 5, 6, 7, 8, 11, 13, 16, 17, 19, 23, 29, 31, 32]
multi_nbr = np.array([1,2,3,5,8,13,21,34,55,89])
plot_nbr = np.arange(0,89)
all_cycles = []
k_v = []
m_v = []
for fftlen in length:
    estimated_cycles = []
    for nbr in multi_nbr:
        benchname = f"bench_planned_multi_{fftlen}_{nbr}"
        cycles = data[benchname]
        estimated_cycles.append(cycles)
    # y = k*x + m
    k, m = np.polyfit(multi_nbr, estimated_cycles, 1)
    k_v.append(k)
    m_v.append(m)
    
    all_cycles.append(estimated_cycles)

    plt.figure(fftlen)
    plt.plot(multi_nbr, estimated_cycles, '*')
    plt.plot(plot_nbr, k*plot_nbr + m)

print("--- Paste in scalar_planner_estimates.rs ---")
print("// --- Begin code generated by tools/fit_butterflies.py --- \n")
for fftlen, k, m in zip(length, k_v, m_v):
    print(f"const BUTTERFLY_SLOPE_{fftlen}: f32 = {k:.5f};")
    print(f"const BUTTERFLY_CONST_{fftlen}: f32 = {m:.5f};")
    print("")
    print(f"pub fn estimate_butterfly_cost_{fftlen}(repeats: usize) -> f32 {{")
    print(f"    BUTTERFLY_SLOPE_{fftlen} * repeats as f32 + BUTTERFLY_CONST_{fftlen}")
    print("}")
    print("")
print("// --- End code generated by tools/fit_butterflies.py --- \n")

#print("\n--- Paste in fit_mixedradixes.py ---")
#for fftlen, k, m in zip(length, k_v, m_v):
#    print(f'    {fftlen}: {{ "slope": {k}, "const": {m}}},')
#
plt.show()

