//! Per-planner adapters between [`Spec`] and each planner's own `Recipe`.
//!
//! The three SIMD planners have structurally identical `Recipe` types, so their adapters are
//! generated by a macro. The scalar one is written out because it differs: it has `RadixN`, and
//! a different set of butterflies with no separate prime-butterfly kind.

use std::any::TypeId;
use std::sync::Arc;

use super::{Spec, TunablePlanner};
use crate::{Fft, FftDirection, FftNum};

/// Panic message used when a spec asks for something a planner cannot express.
fn unsupported(planner: &str, what: &str) -> ! {
    panic!("the {} planner cannot express {}", planner, what)
}

// ---------------------------------------------------------------------------
// Scalar
// ---------------------------------------------------------------------------

/// Butterfly lengths the scalar planner has kernels for.
const SCALAR_BUTTERFLIES: [usize; 20] = [
    2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 16, 17, 19, 23, 24, 27, 29, 31, 32,
];

/// Bases worth trying under Radix4 and RadixN in the scalar planner. These are the sizes its own
/// `design_radixn` chooses between, which are the ones that have been benchmarked upstream.
const SCALAR_RADIX_BASES: [usize; 9] = [5, 6, 7, 8, 9, 12, 16, 24, 27];

pub struct ScalarTuner<T: FftNum> {
    planner: crate::FftPlannerScalar<T>,
}

impl<T: FftNum> ScalarTuner<T> {
    fn to_spec(recipe: &crate::plan::Recipe) -> Arc<Spec> {
        use crate::plan::Recipe;
        Arc::new(match recipe {
            Recipe::Dft(len) => Spec::Dft(*len),
            Recipe::Radix4 { k, base_fft } => Spec::Radix4 {
                k: *k,
                base: Self::to_spec(base_fft),
            },
            Recipe::RadixN { factors, base_fft } => Spec::RadixN {
                radixes: factors.iter().map(|f| f.radix()).collect(),
                base: Self::to_spec(base_fft),
            },
            Recipe::MixedRadix {
                left_fft,
                right_fft,
            } => Spec::MixedRadix {
                left: Self::to_spec(left_fft),
                right: Self::to_spec(right_fft),
                small: false,
            },
            Recipe::MixedRadixSmall {
                left_fft,
                right_fft,
            } => Spec::MixedRadix {
                left: Self::to_spec(left_fft),
                right: Self::to_spec(right_fft),
                small: true,
            },
            Recipe::GoodThomasAlgorithm {
                left_fft,
                right_fft,
            } => Spec::GoodThomas {
                left: Self::to_spec(left_fft),
                right: Self::to_spec(right_fft),
                small: false,
            },
            Recipe::GoodThomasAlgorithmSmall {
                left_fft,
                right_fft,
            } => Spec::GoodThomas {
                left: Self::to_spec(left_fft),
                right: Self::to_spec(right_fft),
                small: true,
            },
            Recipe::RadersAlgorithm { inner_fft } => Spec::Raders {
                inner: Self::to_spec(inner_fft),
            },
            Recipe::BluesteinsAlgorithm { len, inner_fft } => Spec::Bluesteins {
                len: *len,
                inner: Self::to_spec(inner_fft),
            },
            butterfly => Spec::Butterfly(butterfly.len()),
        })
    }

    fn from_spec(spec: &Spec) -> Arc<crate::plan::Recipe> {
        use crate::common::RadixFactor;
        use crate::plan::Recipe;
        Arc::new(match spec {
            Spec::Dft(len) => Recipe::Dft(*len),
            Spec::Radix4 { k, base } => Recipe::Radix4 {
                k: *k,
                base_fft: Self::from_spec(base),
            },
            Spec::RadixN { radixes, base } => Recipe::RadixN {
                factors: radixes
                    .iter()
                    .map(|r| match r {
                        2 => RadixFactor::Factor2,
                        3 => RadixFactor::Factor3,
                        4 => RadixFactor::Factor4,
                        5 => RadixFactor::Factor5,
                        6 => RadixFactor::Factor6,
                        7 => RadixFactor::Factor7,
                        other => unsupported("scalar", &format!("a radix of {}", other)),
                    })
                    .collect::<Vec<_>>()
                    .into_boxed_slice(),
                base_fft: Self::from_spec(base),
            },
            Spec::MixedRadix { left, right, small } => {
                let (left_fft, right_fft) = (Self::from_spec(left), Self::from_spec(right));
                if *small {
                    Recipe::MixedRadixSmall {
                        left_fft,
                        right_fft,
                    }
                } else {
                    Recipe::MixedRadix {
                        left_fft,
                        right_fft,
                    }
                }
            }
            Spec::GoodThomas { left, right, small } => {
                let (left_fft, right_fft) = (Self::from_spec(left), Self::from_spec(right));
                if *small {
                    Recipe::GoodThomasAlgorithmSmall {
                        left_fft,
                        right_fft,
                    }
                } else {
                    Recipe::GoodThomasAlgorithm {
                        left_fft,
                        right_fft,
                    }
                }
            }
            Spec::Raders { inner } => Recipe::RadersAlgorithm {
                inner_fft: Self::from_spec(inner),
            },
            Spec::Bluesteins { len, inner } => Recipe::BluesteinsAlgorithm {
                len: *len,
                inner_fft: Self::from_spec(inner),
            },
            Spec::Butterfly(len) => match len {
                2 => Recipe::Butterfly2,
                3 => Recipe::Butterfly3,
                4 => Recipe::Butterfly4,
                5 => Recipe::Butterfly5,
                6 => Recipe::Butterfly6,
                7 => Recipe::Butterfly7,
                8 => Recipe::Butterfly8,
                9 => Recipe::Butterfly9,
                11 => Recipe::Butterfly11,
                12 => Recipe::Butterfly12,
                13 => Recipe::Butterfly13,
                16 => Recipe::Butterfly16,
                17 => Recipe::Butterfly17,
                19 => Recipe::Butterfly19,
                23 => Recipe::Butterfly23,
                24 => Recipe::Butterfly24,
                27 => Recipe::Butterfly27,
                29 => Recipe::Butterfly29,
                31 => Recipe::Butterfly31,
                32 => Recipe::Butterfly32,
                other => unsupported("scalar", &format!("a butterfly of {}", other)),
            },
        })
    }
}

impl<T: FftNum> TunablePlanner<T> for ScalarTuner<T> {
    fn label() -> &'static str {
        "scalar"
    }

    fn new() -> Self {
        Self {
            planner: crate::FftPlannerScalar::new(),
        }
    }

    fn plan(&mut self, len: usize) -> Arc<Spec> {
        let recipe = self.planner.design_fft_for_len(len);
        Self::to_spec(&recipe)
    }

    fn build(&mut self, spec: &Spec, direction: FftDirection) -> Arc<dyn Fft<T>> {
        super::check_unambiguous(spec, &mut Default::default()).expect("ambiguous recipe");
        let recipe = Self::from_spec(spec);
        let mut planner = crate::FftPlannerScalar::<T>::new();
        planner.build_fft(&recipe, direction)
    }

    fn butterfly_lens() -> Vec<usize> {
        SCALAR_BUTTERFLIES.to_vec()
    }

    fn radix4_bases() -> Vec<usize> {
        SCALAR_RADIX_BASES.to_vec()
    }

    fn has_radixn() -> bool {
        true
    }
}

// ---------------------------------------------------------------------------
// SIMD planners
// ---------------------------------------------------------------------------

/// Butterfly lengths the SIMD planners have dedicated kernels for, excluding their prime
/// butterflies, which are listed separately by each module.
const SIMD_BUTTERFLIES: [usize; 14] = [1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, 16, 24, 32];

/// Bases a SIMD `Radix4` can be built on. The smallest are excluded per element type at runtime,
/// because the kernels need a whole number of vector pairs.
const SIMD_RADIX4_BASES: [usize; 10] = [1, 2, 4, 8, 16, 32, 3, 6, 12, 24];

/// Bases a SIMD `RadixN` can be built on. Wider than the `Radix4` set because `SimdRadixN` needs
/// only a whole number of vectors in the base, not a whole number of vector pairs, so odd bases
/// are legal for f64. These are the sizes `simd_planner::design_radixn` chooses between, plus the
/// neighbouring butterfly lengths, so the sweep can see one factor either side of its pick.
const SIMD_RADIXN_BASES: [usize; 12] = [4, 5, 6, 7, 8, 9, 10, 12, 15, 16, 24, 32];

/// Generates a `TunablePlanner` adapter for one of the SIMD planners.
///
/// They are identical apart from which module their `Recipe`, planner and prime butterflies live
/// in, so this exists to keep three copies of the same conversion from drifting apart.
macro_rules! simd_adapter {
    ($tuner:ident, $label:literal, $planner:path, $recipe:path, $prime_lens:path) => {
        pub struct $tuner<T: FftNum> {
            planner: $planner,
        }

        impl<T: FftNum> $tuner<T> {
            fn to_spec(recipe: &$recipe) -> Arc<Spec> {
                use $recipe as R;
                Arc::new(match recipe {
                    R::Dft(len) => Spec::Dft(*len),
                    R::Radix4 { k, base_fft } => Spec::Radix4 {
                        k: *k,
                        base: Self::to_spec(base_fft),
                    },
                    R::RadixN { factors, base_fft } => Spec::RadixN {
                        radixes: factors.iter().map(|f| f.radix()).collect(),
                        base: Self::to_spec(base_fft),
                    },
                    R::MixedRadix {
                        left_fft,
                        right_fft,
                    } => Spec::MixedRadix {
                        left: Self::to_spec(left_fft),
                        right: Self::to_spec(right_fft),
                        small: false,
                    },
                    R::MixedRadixSmall {
                        left_fft,
                        right_fft,
                    } => Spec::MixedRadix {
                        left: Self::to_spec(left_fft),
                        right: Self::to_spec(right_fft),
                        small: true,
                    },
                    R::GoodThomasAlgorithm {
                        left_fft,
                        right_fft,
                    } => Spec::GoodThomas {
                        left: Self::to_spec(left_fft),
                        right: Self::to_spec(right_fft),
                        small: false,
                    },
                    R::GoodThomasAlgorithmSmall {
                        left_fft,
                        right_fft,
                    } => Spec::GoodThomas {
                        left: Self::to_spec(left_fft),
                        right: Self::to_spec(right_fft),
                        small: true,
                    },
                    R::RadersAlgorithm { inner_fft } => Spec::Raders {
                        inner: Self::to_spec(inner_fft),
                    },
                    R::BluesteinsAlgorithm { len, inner_fft } => Spec::Bluesteins {
                        len: *len,
                        inner: Self::to_spec(inner_fft),
                    },
                    butterfly => Spec::Butterfly(butterfly.len()),
                })
            }

            fn from_spec(spec: &Spec) -> Arc<$recipe> {
                use $recipe as R;
                Arc::new(match spec {
                    Spec::Dft(len) => R::Dft(*len),
                    Spec::Radix4 { k, base } => R::Radix4 {
                        k: *k,
                        base_fft: Self::from_spec(base),
                    },
                    Spec::RadixN { radixes, base } => R::RadixN {
                        factors: radixes
                            .iter()
                            .map(|r| match r {
                                2 => crate::common::RadixFactor::Factor2,
                                3 => crate::common::RadixFactor::Factor3,
                                4 => crate::common::RadixFactor::Factor4,
                                5 => crate::common::RadixFactor::Factor5,
                                6 => crate::common::RadixFactor::Factor6,
                                7 => crate::common::RadixFactor::Factor7,
                                other => unsupported($label, &format!("a radix of {}", other)),
                            })
                            .collect::<Vec<_>>()
                            .into_boxed_slice(),
                        base_fft: Self::from_spec(base),
                    },
                    Spec::MixedRadix { left, right, small } => {
                        let (left_fft, right_fft) = (Self::from_spec(left), Self::from_spec(right));
                        if *small {
                            R::MixedRadixSmall {
                                left_fft,
                                right_fft,
                            }
                        } else {
                            R::MixedRadix {
                                left_fft,
                                right_fft,
                            }
                        }
                    }
                    Spec::GoodThomas { left, right, small } => {
                        let (left_fft, right_fft) = (Self::from_spec(left), Self::from_spec(right));
                        if *small {
                            R::GoodThomasAlgorithmSmall {
                                left_fft,
                                right_fft,
                            }
                        } else {
                            R::GoodThomasAlgorithm {
                                left_fft,
                                right_fft,
                            }
                        }
                    }
                    Spec::Raders { inner } => R::RadersAlgorithm {
                        inner_fft: Self::from_spec(inner),
                    },
                    Spec::Bluesteins { len, inner } => R::BluesteinsAlgorithm {
                        len: *len,
                        inner_fft: Self::from_spec(inner),
                    },
                    Spec::Butterfly(len) => match len {
                        1 => R::Butterfly1,
                        2 => R::Butterfly2,
                        3 => R::Butterfly3,
                        4 => R::Butterfly4,
                        5 => R::Butterfly5,
                        6 => R::Butterfly6,
                        8 => R::Butterfly8,
                        9 => R::Butterfly9,
                        10 => R::Butterfly10,
                        12 => R::Butterfly12,
                        15 => R::Butterfly15,
                        16 => R::Butterfly16,
                        24 => R::Butterfly24,
                        32 => R::Butterfly32,
                        len if $prime_lens().contains(len) => R::PrimeButterfly { len: *len },
                        other => unsupported($label, &format!("a butterfly of {}", other)),
                    },
                })
            }
        }

        impl<T: FftNum> TunablePlanner<T> for $tuner<T> {
            fn label() -> &'static str {
                $label
            }

            fn new() -> Self {
                Self {
                    planner: <$planner>::new()
                        .expect(concat!("this machine does not support ", $label)),
                }
            }

            fn plan(&mut self, len: usize) -> Arc<Spec> {
                let recipe = self.planner.design_fft_for_len(len);
                Self::to_spec(&recipe)
            }

            fn build(&mut self, spec: &Spec, direction: FftDirection) -> Arc<dyn Fft<T>> {
                super::check_unambiguous(spec, &mut Default::default()).expect("ambiguous recipe");
                let recipe = Self::from_spec(spec);
                let mut planner =
                    <$planner>::new().expect(concat!("this machine does not support ", $label));
                planner.build_fft(&recipe, direction)
            }

            fn butterfly_lens() -> Vec<usize> {
                let mut lens: Vec<usize> = SIMD_BUTTERFLIES.to_vec();
                lens.extend_from_slice($prime_lens());
                lens.sort_unstable();
                lens.dedup();
                lens
            }

            fn radix4_bases() -> Vec<usize> {
                // The kernels require the base length to be a whole number of vector pairs,
                // which rules out the smallest bases, and rules out more of them for f32.
                let multiple = if TypeId::of::<T>() == TypeId::of::<f32>() {
                    4
                } else {
                    2
                };
                SIMD_RADIX4_BASES
                    .iter()
                    .copied()
                    .filter(|base| base % multiple == 0)
                    .collect()
            }

            fn radixn_bases() -> Vec<usize> {
                // `SimdRadixN` only asserts a whole number of vectors in the base, so for f64
                // every base is legal and for f32 the odd ones are not.
                let multiple = crate::simd::simd_planner::complex_per_vector::<T>();
                SIMD_RADIXN_BASES
                    .iter()
                    .copied()
                    .filter(|base| base % multiple == 0)
                    .collect()
            }

            fn has_radixn() -> bool {
                true
            }
        }
    };
}

#[cfg(all(target_arch = "aarch64", feature = "neon"))]
simd_adapter!(
    NeonTuner,
    "neon",
    crate::FftPlannerNeon<T>,
    crate::neon::neon_planner::Recipe,
    crate::neon::neon_prime_butterflies::prime_butterfly_lens
);

#[cfg(all(target_arch = "x86_64", feature = "sse"))]
simd_adapter!(
    SseTuner,
    "sse",
    crate::FftPlannerSse<T>,
    crate::sse::sse_planner::Recipe,
    crate::sse::sse_prime_butterflies::prime_butterfly_lens
);

#[cfg(all(target_arch = "wasm32", feature = "wasm_simd"))]
simd_adapter!(
    WasmSimdTuner,
    "wasm_simd",
    crate::FftPlannerWasmSimd<T>,
    crate::wasm_simd::wasm_simd_planner::Recipe,
    crate::wasm_simd::wasm_simd_prime_butterflies::prime_butterfly_lens
);
