//! Emit a fitted model as a Rust source file for the Neon planner to include.
//!
//! The generated file is data, not logic: measured primitive costs and the fitted per-element
//! overheads. Keeping it separate from the planner keeps the boundary between "measured on some
//! machine" and "written by a person" obvious, which is what ejmahler asked for on PR #38.

use crate::model::Model;

/// Costs are stored relative to Butterfly32 rather than in nanoseconds, so that a table fitted
/// on one machine is at least meaningfully comparable on another. The planner only ever
/// compares costs, so the unit cancels.
const REFERENCE_BUTTERFLY: usize = 32;

pub fn emit(model: &Model, element_type: &str, planner: &str) -> String {
    let unit = model
        .butterfly
        .get(&REFERENCE_BUTTERFLY)
        .copied()
        .expect("butterfly 32 must be measured, it is the normalisation reference");

    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by tools/planner_tuning. Do not edit by hand.\n\
         //\n\
         // Costs for the {} planner, relative to Butterfly{} for {} elements. Regenerate with:\n\
         //     planner_tuning emit --planner {} LENGTHS...\n\n",
        planner, REFERENCE_BUTTERFLY, element_type, planner
    ));

    let mut butterflies: Vec<(&usize, &f64)> = model.butterfly.iter().collect();
    butterflies.sort_by_key(|(len, _)| **len);
    out.push_str("/// Measured cost of one butterfly, by length.\n");
    out.push_str("pub(crate) const BUTTERFLY_COST: &[(usize, f32)] = &[\n");
    for (len, cost) in butterflies {
        out.push_str(&format!("    ({}, {:.5}),\n", len, cost / unit));
    }
    out.push_str("];\n\n");

    let mut shapes: Vec<(&(usize, u32), &f64)> = model.radix4.iter().collect();
    shapes.sort_by_key(|((base, k), _)| (*base, *k));
    out.push_str("/// Measured cost of one Radix4, by (base length, k).\n");
    out.push_str("pub(crate) const RADIX4_COST: &[(usize, u32, f32)] = &[\n");
    for ((base, k), cost) in shapes {
        out.push_str(&format!("    ({}, {}, {:.5}),\n", base, k, cost / unit));
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// Fitted overhead per element, as (log2 of working set, cost), to be interpolated.\n\
         ///\n\
         /// These are curves rather than constants because the scattered reindexing in\n\
         /// GoodThomas and Rader's costs sharply more once the array outgrows L1.\n",
    );
    for (name, key) in [
        ("MIXEDRADIX", "mr"),
        ("MIXEDRADIX_SMALL", "mrs"),
        ("GOODTHOMAS", "gt"),
        ("GOODTHOMAS_SMALL", "gts"),
        ("RADERS", "rad"),
        ("BLUESTEINS", "bs"),
    ] {
        let table = model
            .overhead
            .get(key)
            .unwrap_or_else(|| panic!("overhead '{}' was never fitted", key));
        let entries: Vec<String> = table
            .iter()
            .map(|(bucket, value)| format!("({}, {:.6})", bucket, value / unit))
            .collect();
        out.push_str(&format!(
            "pub(crate) const {}_OVERHEAD: &[(u32, f32)] = &[{}];\n",
            name,
            entries.join(", ")
        ));
    }
    out
}
