import numpy
numpy.random.seed(100)

tests = [{
	"name": "known_test_data_2d",
	"dimensions": 2,
	"shapes": [
		[2, 2],
		[3, 3],
		[2, 3],
		[2, 10],
		[3, 2],
		[10, 2],
	],
},{
	"name": "known_test_data_3d",
	"dimensions": 3,
	"shapes": [
		[2, 2, 2],
		[3, 3, 3],
		[2, 3, 5],
		[5, 3, 2],
	],
},{
	"name": "known_test_data_4d",
	"dimensions": 4,
	"shapes": [
		[2, 2, 2, 2],
		[3, 3, 3, 3],
		[2, 3, 5, 7],
		[7, 5, 3, 2],
	],
},
]

print("// NOTE: This file was autogenerated using tools/gen_multimensional_test_data.py\n")

print("use num_complex::Complex;\n")

print("pub struct KnownTestData<const D: usize> {")
print("    pub shape: [usize; D],")
print("    pub expected_in: Vec<Complex<f32>>,")
print("    pub expected_out: Vec<Complex<f32>>,")
print("}\n")

for t in tests:
	print(f'pub fn {t["name"]}() -> Vec<KnownTestData<{t["dimensions"]}>> {{')
	print("    vec![")

	for s in t["shapes"]:
		values_in = numpy.random.rand(*s) + 1j * numpy.random.rand(*s)
		values_out = numpy.fft.fftn(values_in)

		flat_in = numpy.ndarray.flatten(values_in)
		flat_out = numpy.ndarray.flatten(values_out)

		print(f"        KnownTestData {{")
		print(f"            shape: {s},")
		print(f"            expected_in: vec![")
		for value in flat_in:
			print(f"                Complex::new({value.real:.7f}, {value.imag:.7}),")
		print(f"            ],")
		print(f"            expected_out: vec![")
		for value in flat_out:
			print(f"                Complex::new({value.real:.7f}, {value.imag:.7f}),")
		print(f"            ],")
		print(f"        }},")
	print("    ]")
	print("}\n")