use crate::plan::Recipe;
use std::sync::Arc;

// All the code below is generated by the scripts in the tools folder

// --- Begin code generated by tools/estimates/fit_butterflies.py ---

const BUTTERFLY_SLOPE_2: f32 = 0.14240;
const BUTTERFLY_CONST_2: f32 = 0.47316;

pub fn estimate_butterfly_cost_2(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_2 * repeats as f32 + BUTTERFLY_CONST_2
}

const BUTTERFLY_SLOPE_3: f32 = 0.34894;
const BUTTERFLY_CONST_3: f32 = 0.55279;

pub fn estimate_butterfly_cost_3(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_3 * repeats as f32 + BUTTERFLY_CONST_3
}

const BUTTERFLY_SLOPE_4: f32 = 0.69365;
const BUTTERFLY_CONST_4: f32 = 0.36071;

pub fn estimate_butterfly_cost_4(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_4 * repeats as f32 + BUTTERFLY_CONST_4
}

const BUTTERFLY_SLOPE_5: f32 = 1.16146;
const BUTTERFLY_CONST_5: f32 = 0.49980;

pub fn estimate_butterfly_cost_5(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_5 * repeats as f32 + BUTTERFLY_CONST_5
}

const BUTTERFLY_SLOPE_6: f32 = 0.97944;
const BUTTERFLY_CONST_6: f32 = 0.99706;

pub fn estimate_butterfly_cost_6(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_6 * repeats as f32 + BUTTERFLY_CONST_6
}

const BUTTERFLY_SLOPE_7: f32 = 2.37939;
const BUTTERFLY_CONST_7: f32 = 0.65005;

pub fn estimate_butterfly_cost_7(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_7 * repeats as f32 + BUTTERFLY_CONST_7
}

const BUTTERFLY_SLOPE_8: f32 = 2.69957;
const BUTTERFLY_CONST_8: f32 = 0.98856;

pub fn estimate_butterfly_cost_8(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_8 * repeats as f32 + BUTTERFLY_CONST_8
}

const BUTTERFLY_SLOPE_11: f32 = 5.26259;
const BUTTERFLY_CONST_11: f32 = 0.52859;

pub fn estimate_butterfly_cost_11(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_11 * repeats as f32 + BUTTERFLY_CONST_11
}

const BUTTERFLY_SLOPE_13: f32 = 7.22608;
const BUTTERFLY_CONST_13: f32 = 0.55906;

pub fn estimate_butterfly_cost_13(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_13 * repeats as f32 + BUTTERFLY_CONST_13
}

const BUTTERFLY_SLOPE_16: f32 = 11.16610;
const BUTTERFLY_CONST_16: f32 = 0.14660;

pub fn estimate_butterfly_cost_16(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_16 * repeats as f32 + BUTTERFLY_CONST_16
}

const BUTTERFLY_SLOPE_17: f32 = 13.04313;
const BUTTERFLY_CONST_17: f32 = 0.55663;

pub fn estimate_butterfly_cost_17(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_17 * repeats as f32 + BUTTERFLY_CONST_17
}

const BUTTERFLY_SLOPE_19: f32 = 16.58822;
const BUTTERFLY_CONST_19: f32 = 0.25521;

pub fn estimate_butterfly_cost_19(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_19 * repeats as f32 + BUTTERFLY_CONST_19
}

const BUTTERFLY_SLOPE_23: f32 = 42.08871;
const BUTTERFLY_CONST_23: f32 = 0.59270;

pub fn estimate_butterfly_cost_23(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_23 * repeats as f32 + BUTTERFLY_CONST_23
}

const BUTTERFLY_SLOPE_29: f32 = 84.30511;
const BUTTERFLY_CONST_29: f32 = 1.61285;

pub fn estimate_butterfly_cost_29(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_29 * repeats as f32 + BUTTERFLY_CONST_29
}

const BUTTERFLY_SLOPE_31: f32 = 100.00381;
const BUTTERFLY_CONST_31: f32 = 0.67616;

pub fn estimate_butterfly_cost_31(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_31 * repeats as f32 + BUTTERFLY_CONST_31
}

const BUTTERFLY_SLOPE_32: f32 = 37.36887;
const BUTTERFLY_CONST_32: f32 = 0.05856;

pub fn estimate_butterfly_cost_32(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_32 * repeats as f32 + BUTTERFLY_CONST_32
}

// --- End code generated by tools/estimates/fit_butterflies.py ---

// --- Begin code generated by tools/estimates/fit_radix4.py ---

const RADIX4_CONST: f32 = 1.70408;
const RADIX4_SLOPE: f32 = 0.24548;
const RADIX4_LOGSLOPE: f32 = 0.22164;

pub fn estimate_radix4_cost(len: usize, repeats: usize) -> f32 {
    let f_len = len as f32;
    (RADIX4_CONST + RADIX4_SLOPE * f_len + RADIX4_LOGSLOPE * f_len * f_len.ln()) * repeats as f32
}

// --- End code generated by tools/estimates/fit_radix4.py ---

// --- Begin code generated by tools/estimates/fit_raders.py ---

const RADERS_CONST: f32 = -9.79820;
const RADERS_SLOPE: f32 = 2.34611;

pub fn estimate_raders_cost(inner_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    (RADERS_CONST + RADERS_SLOPE * (inner_fft.len() + 1) as f32 + 2.0 * inner_fft.cost(1))
        * repeats as f32
}

// --- End code generated by tools/estimates/fit_raders.py ---

// --- Begin code generated by tools/estimates/fit_bluesteins.py ---

const BLUESTEINS_CONST: f32 = 10.32568;
const BLUESTEINS_LEN_SLOPE: f32 = 0.32684;
const BLUESTEINS_INNER_LEN_SLOPE: f32 = 0.36229;

pub fn estimate_bluesteins_cost(len: usize, inner_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    (BLUESTEINS_CONST
        + BLUESTEINS_INNER_LEN_SLOPE * inner_fft.len() as f32
        + BLUESTEINS_LEN_SLOPE * len as f32
        + 2.0 * inner_fft.cost(1))
        * repeats as f32
}

// --- End code generated by tools/estimates/fit_bluesteins.py ---

// --- Begin code generated by tools/estimates/fit_mixedradixes.py ---

const MIXEDRADIX_SLOPE: f32 = 0.75121;
const MIXEDRADIX_CONST: f32 = 6.60985;

pub fn estimate_mixedradix_cost(
    len: usize,
    left_fft: &Arc<Recipe>,
    right_fft: &Arc<Recipe>,
    repeats: usize,
) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = MIXEDRADIX_SLOPE * (len as f32) + MIXEDRADIX_CONST;
    (inners_cost + twiddle_cost) * repeats as f32
}

const MIXEDRADIXSMALL_SLOPE: f32 = 0.53415;
const MIXEDRADIXSMALL_CONST: f32 = 3.54333;

pub fn estimate_mixedradixsmall_cost(
    len: usize,
    left_fft: &Arc<Recipe>,
    right_fft: &Arc<Recipe>,
    repeats: usize,
) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = MIXEDRADIXSMALL_SLOPE * (len as f32) + MIXEDRADIXSMALL_CONST;
    (inners_cost + twiddle_cost) * repeats as f32
}

const GOODTHOMAS_SLOPE: f32 = 1.19135;
const GOODTHOMAS_CONST: f32 = 0.80663;

pub fn estimate_goodthomas_cost(
    len: usize,
    left_fft: &Arc<Recipe>,
    right_fft: &Arc<Recipe>,
    repeats: usize,
) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = GOODTHOMAS_SLOPE * (len as f32) + GOODTHOMAS_CONST;
    (inners_cost + twiddle_cost) * repeats as f32
}

const GOODTHOMASSMALL_SLOPE: f32 = 0.42891;
const GOODTHOMASSMALL_CONST: f32 = 1.54860;

pub fn estimate_goodthomassmall_cost(
    len: usize,
    left_fft: &Arc<Recipe>,
    right_fft: &Arc<Recipe>,
    repeats: usize,
) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = GOODTHOMASSMALL_SLOPE * (len as f32) + GOODTHOMASSMALL_CONST;
    (inners_cost + twiddle_cost) * repeats as f32
}

// --- End code generated by tools/estimates/fit_mixedradixes.py ---
