use crate::plan::Recipe;
use std::sync::Arc;

// All the code below is generated by the scripts in the tools folder

// --- Begin code generated by tools/fit_butterflies.py --- 

const BUTTERFLY_SLOPE_2: f32 = 0.66734;
const BUTTERFLY_CONST_2: f32 = 1.58435;

pub fn estimate_butterfly_cost_2(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_2 * repeats as f32 + BUTTERFLY_CONST_2
}

const BUTTERFLY_SLOPE_3: f32 = 1.66062;
const BUTTERFLY_CONST_3: f32 = 2.03971;

pub fn estimate_butterfly_cost_3(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_3 * repeats as f32 + BUTTERFLY_CONST_3
}

const BUTTERFLY_SLOPE_4: f32 = 3.01666;
const BUTTERFLY_CONST_4: f32 = 2.01515;

pub fn estimate_butterfly_cost_4(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_4 * repeats as f32 + BUTTERFLY_CONST_4
}

const BUTTERFLY_SLOPE_5: f32 = 5.01921;
const BUTTERFLY_CONST_5: f32 = 4.85616;

pub fn estimate_butterfly_cost_5(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_5 * repeats as f32 + BUTTERFLY_CONST_5
}

const BUTTERFLY_SLOPE_6: f32 = 4.44640;
const BUTTERFLY_CONST_6: f32 = 5.08810;

pub fn estimate_butterfly_cost_6(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_6 * repeats as f32 + BUTTERFLY_CONST_6
}

const BUTTERFLY_SLOPE_7: f32 = 10.29222;
const BUTTERFLY_CONST_7: f32 = 4.74967;

pub fn estimate_butterfly_cost_7(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_7 * repeats as f32 + BUTTERFLY_CONST_7
}

const BUTTERFLY_SLOPE_8: f32 = 11.57538;
const BUTTERFLY_CONST_8: f32 = 3.50875;

pub fn estimate_butterfly_cost_8(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_8 * repeats as f32 + BUTTERFLY_CONST_8
}

const BUTTERFLY_SLOPE_11: f32 = 23.30122;
const BUTTERFLY_CONST_11: f32 = 3.24180;

pub fn estimate_butterfly_cost_11(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_11 * repeats as f32 + BUTTERFLY_CONST_11
}

const BUTTERFLY_SLOPE_13: f32 = 32.64988;
const BUTTERFLY_CONST_13: f32 = -3.41227;

pub fn estimate_butterfly_cost_13(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_13 * repeats as f32 + BUTTERFLY_CONST_13
}

const BUTTERFLY_SLOPE_16: f32 = 46.69326;
const BUTTERFLY_CONST_16: f32 = 1.18576;

pub fn estimate_butterfly_cost_16(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_16 * repeats as f32 + BUTTERFLY_CONST_16
}

const BUTTERFLY_SLOPE_17: f32 = 57.72139;
const BUTTERFLY_CONST_17: f32 = 8.13590;

pub fn estimate_butterfly_cost_17(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_17 * repeats as f32 + BUTTERFLY_CONST_17
}

const BUTTERFLY_SLOPE_19: f32 = 73.07633;
const BUTTERFLY_CONST_19: f32 = 37.33667;

pub fn estimate_butterfly_cost_19(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_19 * repeats as f32 + BUTTERFLY_CONST_19
}

const BUTTERFLY_SLOPE_23: f32 = 178.74661;
const BUTTERFLY_CONST_23: f32 = -8.04662;

pub fn estimate_butterfly_cost_23(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_23 * repeats as f32 + BUTTERFLY_CONST_23
}

const BUTTERFLY_SLOPE_29: f32 = 354.65587;
const BUTTERFLY_CONST_29: f32 = -14.35064;

pub fn estimate_butterfly_cost_29(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_29 * repeats as f32 + BUTTERFLY_CONST_29
}

const BUTTERFLY_SLOPE_31: f32 = 421.03209;
const BUTTERFLY_CONST_31: f32 = -3.74129;

pub fn estimate_butterfly_cost_31(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_31 * repeats as f32 + BUTTERFLY_CONST_31
}

const BUTTERFLY_SLOPE_32: f32 = 160.81762;
const BUTTERFLY_CONST_32: f32 = -3.78703;

pub fn estimate_butterfly_cost_32(repeats: usize) -> f32 {
    BUTTERFLY_SLOPE_32 * repeats as f32 + BUTTERFLY_CONST_32
}

// --- End code generated by tools/fit_butterflies.py --- 

// --- Begin code generated by tools/fit_radix4.py --- 

const RADIX4_SHORT_CONST: f32 = 1.47476;
const RADIX4_SHORT_SLOPE: f32 = 3.33803;
const RADIX4_SHORT_EXP: f32 = 1.20978;
const RADIX4_LONG_CONST: f32 = 471.66969;
const RADIX4_LONG_SLOPE: f32 = 1.64004;
const RADIX4_LONG_EXP: f32 = 1.20978;

pub fn estimate_radix4_cost(len: usize, repeats: usize) -> f32 {
    if len <= 128 {
        (RADIX4_SHORT_CONST
            + RADIX4_SHORT_SLOPE * (len as f32).powf(RADIX4_SHORT_EXP))
            * repeats as f32
    } else {
        (RADIX4_LONG_CONST
            + RADIX4_LONG_SLOPE * (len as f32).powf(RADIX4_LONG_EXP))
            * repeats as f32
    }
}

// --- End code generated by tools/fit_radix4.py --- 

// --- Begin code generated by tools/fit_raders.py --- 

const RADERS_CONST: f32 = -183.65998;
const RADERS_SLOPE: f32 = 10.30029;

pub fn estimate_raders_cost(inner_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    (RADERS_CONST
        + RADERS_SLOPE * (inner_fft.len() + 1) as f32
        + 2.0 * inner_fft.cost(1))
        * repeats as f32
}

// --- End code generated by tools/fit_raders.py ---


// --- Begin code generated by tools/fit_bluesteins.py --- 

const BLUESTEINS_CONST: f32 = 71.07762;
const BLUESTEINS_LEN_SLOPE: f32 = 1.29934;
const BLUESTEINS_INNER_LEN_SLOPE: f32 = 1.70852;

pub fn estimate_bluesteins_cost(len: usize, inner_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    (BLUESTEINS_CONST
        + BLUESTEINS_INNER_LEN_SLOPE * inner_fft.len() as f32
        + BLUESTEINS_LEN_SLOPE * len as f32
        + 2.0 * inner_fft.cost(1))
        * repeats as f32
}

// --- End code generated by tools/fit_bluesteins.py --- 

// --- Begin code generated by tools/fit_mixedradixes.py --- 

const MIXEDRADIX_SLOPE: f32 = 0.22160;
const MIXEDRADIX_EXP: f32 = 1.27359;

pub fn estimate_mixedradix_cost(len: usize, left_fft: &Arc<Recipe>, right_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = MIXEDRADIX_SLOPE * (len as f32).powf(MIXEDRADIX_EXP);
    (inners_cost + twiddle_cost) * repeats as f32
}

const MIXEDRADIXSMALL_SLOPE: f32 = 4.54529;
const MIXEDRADIXSMALL_EXP: f32 = 0.90258;

pub fn estimate_mixedradixsmall_cost(len: usize, left_fft: &Arc<Recipe>, right_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = MIXEDRADIXSMALL_SLOPE * (len as f32).powf(MIXEDRADIXSMALL_EXP);
    (inners_cost + twiddle_cost) * repeats as f32
}

const GOODTHOMAS_SLOPE: f32 = 0.14090;
const GOODTHOMAS_EXP: f32 = 1.34598;

pub fn estimate_goodthomas_cost(len: usize, left_fft: &Arc<Recipe>, right_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = GOODTHOMAS_SLOPE * (len as f32).powf(GOODTHOMAS_EXP);
    (inners_cost + twiddle_cost) * repeats as f32
}

const GOODTHOMASSMALL_SLOPE: f32 = 2.54734;
const GOODTHOMASSMALL_EXP: f32 = 0.96064;

pub fn estimate_goodthomassmall_cost(len: usize, left_fft: &Arc<Recipe>, right_fft: &Arc<Recipe>, repeats: usize) -> f32 {
    let inners_cost = left_fft.cost(right_fft.len()) + right_fft.cost(left_fft.len());
    let twiddle_cost = GOODTHOMASSMALL_SLOPE * (len as f32).powf(GOODTHOMASSMALL_EXP);
    (inners_cost + twiddle_cost) * repeats as f32
}

// --- End code generated by tools/fit_mixedradixes.py --- 

